name: 'CI Steps'
description: 'Run linter, tests and build'

inputs:
  skip-build:
    description: 'Skip build step'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run linter
      shell: bash
      run: npm run lint

    - name: Run tests
      shell: bash
      run: npm run test:run

    - name: Build project
      if: inputs.skip-build != 'true'
      shell: bash
      run: npm run build

